INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME) SELECT * FROM (
SELECT 'Paul', 'Morphy' UNION
SELECT 'Bobby', 'Fischer' UNION
SELECT 'Reuben', 'Fine' UNION
SELECT 'Fabiano', 'Caruana' UNION
SELECT 'Nigel', 'Short'
) x WHERE NOT EXISTS(SELECT * FROM ATTENDEE);